### ISSUE TITLE
Cannot preview FsUnit nuget package

### ISSUE THREAD

**Issue by sergey-tihon** [eridem/vscode-nupkg#1]
This is the sample of nupkg that I cannot preview
https://www.nuget.org/packages/FsUnit/3.0.0

![apr-03-2017 21-17-01](https://cloud.githubusercontent.com/assets/1197905/24623981/f9839426-18b2-11e7-8d71-2bf00e5a35ec.gif)

The error message
```
shell.ts:426 Cannot read property 'targetFramework' of undefined: TypeError: Cannot read property 'targetFramework' of undefined
    at dependencyKeys.forEach.k (/Users/sergey/.vscode/extensions/eridem.vscode-nupkg-0.0.4/out/src/nupkg-utils.js:21:42)
    at Array.forEach (native)
    at createNuGetAsText (/Users/sergey/.vscode/extensions/eridem.vscode-nupkg-0.0.4/out/src/nupkg-utils.js:19:24)
    at /Users/sergey/.vscode/extensions/eridem.vscode-nupkg-0.0.4/out/src/nupkg-utils.js:45:44
    at Parser.<anonymous> (/Users/sergey/.vscode/extensions/eridem.vscode-nupkg-0.0.4/node_modules/smart-nupkg-metadata-reader/smartnupkgmetadatareader.js:32:11)
    at emitOne (events.js:96:13)
    at Parser.emit (events.js:188:7)
    at Object.onclosetag (/Users/sergey/.vscode/extensions/eridem.vscode-nupkg-0.0.4/node_modules/xml2js/lib/xml2js.js:447:26)
    at emit (/Users/sergey/.vscode/extensions/eridem.vscode-nupkg-0.0.4/node_modules/sax/lib/sax.js:640:35)
    at emitNode (/Users/sergey/.vscode/extensions/eridem.vscode-nupkg-0.0.4/node_modules/sax/lib/sax.js:645:5)
```

<img width="800" alt="2017-04-03_2120" src="https://cloud.githubusercontent.com/assets/1197905/24624097/69d2b748-18b3-11e7-96d1-d30832c458b4.png">

**Comment by sergey-tihon** [comment]
Here is a file 
[FsUnit.3.0.1.nupkg.zip](https://github.com/eridem/vscode-nupkg/files/890959/FsUnit.3.0.1.nupkg.zip)

**Comment by eridem** [comment]
thanks @sergey-tihon, I will have a look now 👍

**Comment by sergey-tihon** [comment]
@eridem Thank for the extension.
I do not know alternatives to preview nuokg on macOS without pure unzip and open.

**Comment by eridem** [comment]
Fix: https://github.com/eridem/vscode-nupkg/pull/3
Will deploy in next release.
